#ifndef CG_DWF_CONFIG_H
#define CG_DWF_CONFIG_H

#include "cg-dwf-config-internal.h"
#define DWF_PACKAGE PACKAGE
#define DWF_BUGREPORT BUGREPORT
#define DWF_PACKAGE_NAME PACKAGE_NAME
#define DWF_PACKAGE_STRING PACKAGE_STRING
#define DWF_PACKAGE_TARNAME PACKAGE_TARNAME
#define DWF_PACKAGE_VERSION PACKAGE_VERSION
#define DWF_VERSION VERSION

#undef PACKAGE
#undef PACKAGE_BUGREPORT
#undef PACKAGE_NAME
#undef PACKAGE_STRING
#undef PACKAGE_TARNAME
#undef PACKAGE_VERSION
#undef VERSION

#endif
