#!/bin/sh

if [ $# -ne 2 ]; then
   echo "usage: $0 exe type"
   exit 1
fi

exe="$1"
type="$2"


for c in 0 1 2; do
  for d in 0 1 2 3; do
     for x in 8 9 0 1 5; do
       for s in 14 15 0 1 2 7; do
         for re in 0 1; do
            $exe `pwd`/dwf-op-$type \
                      10 10 10 20 16 \
                      13 0.0625 \
                  $x 0 0 0 $s $c $d $re
         done
       done
     done
   done
done


